export const data = [
  {
    id: 1,
    name: 't-shirt grey',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/4_XauX8Aq5h.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053676',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 20,
    reviews: 134,
    rating: 2.2,
    category: 'men',
  },
  {
    id: 2,
    name: 't-shirt blue',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/7_KPDcPwOlXd.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053654',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 30,
    reviews: 250,
    rating: 4.4,
    category: 'men',
  },
  {
    id: 3,
    name: 't-shirt black',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/5_MnSb0yk9l.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053621',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 35,
    reviews: 1500,
    rating: 4.9,
    category: 'men',
  },
  {
    id: 4,
    name: 't-shirt green',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/10_G61vZ1zelM.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053464',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 40,
    reviews: 5000,
    rating: 5,
    category: 'men',
  },
  {
    id: 5,
    name: 't-shirt yellow',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/8_Lf3NdAxAFV.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053306',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 12,
    reviews: 456,
    rating: 1.4,
    category: 'men',
  },
  {
    id: 6,
    name: 't-shirt pink',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/9_5SGZDc0WW.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053255',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 13,
    reviews: 134,
    rating: 1,
    category: 'men',
  },
  {
    id: 7,
    name: 't-shirt red',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/1_Ipqi8KXMa.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053254',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 19,
    reviews: 554,
    rating: 3,
    category: 'men',
  },
  {
    id: 8,
    name: 't-shirt black',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/2_tfWoofmc1.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053193',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 42,
    reviews: 895,
    rating: 4.3,
    category: 'men',
  },
  {
    id: 9,
    name: 't-shirt white',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/3_A3XYEbLZD.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053130',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 99,
    reviews: 83,
    rating: 2.5,
    category: 'men',
  },
  {
    id: 10,
    name: 't-shirt red & black',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/men/6_hp7iFnZXF.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663653053099',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 10,
    reviews: 98,
    rating: 3,
    category: 'men',
  },
  {
    id: 11,
    name: `Shirts, women's yellow sleeveless blouse`,
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg_aEMMizM9w.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488971',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 40,
    reviews: 343,
    rating: 2.5,
    category: 'women',
  },
  {
    id: 12,
    name: 'sky blue shirt',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__7__EXciot1Yp.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488925',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 55,
    reviews: 423,
    rating: 4,
    category: 'women',
  },
  {
    id: 13,
    name: 'Blouse T-shirt Sleeve Dress',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__1__qlYjpyJaG.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488804',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 99,
    reviews: 34,
    rating: 3,
    category: 'women',
  },
  {
    id: 14,
    name: 'T-shirt Sleeve Collar Knitting',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__6__3znhmeFwu.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488860',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 23,
    reviews: 100,
    rating: 1.2,
    category: 'women',
  },
  {
    id: 15,
    name: 'Hoodie T-shirt Bluza',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__3__c3ogJaOjcr.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488697',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 44,
    reviews: 12,
    rating: 5,
    category: 'women',
  },
  {
    id: 16,
    name: 't-shirt black & white',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__9____BeuNsZr.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488579',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 5,
    reviews: 4,
    rating: 3.3,
    category: 'women',
  },
  {
    id: 17,
    name: 't-shirt pink women',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__8__d1bv5xYAD.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488546',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 90,
    reviews: 45,
    rating: 1.2,
    category: 'women',
  },
  {
    id: 18,
    name: 'T-shirt, purple',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__2__g2qiTFxyW.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488478',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 45,
    reviews: 65,
    rating: 4.5,
    category: 'women',
  },
  {
    id: 19,
    name: 'T-shirt pink strong',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__5__TaylPW0j-H.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488402',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 12,
    reviews: 99,
    rating: 4.6,
    category: 'women',
  },
  {
    id: 20,
    name: 't-shirt white women',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/woman/pngegg__4__BSfjFn7s9.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654488096',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 32,
    reviews: 102,
    rating: 2.5,
    category: 'women',
  },
  {
    id: 21,
    name: 'kids shirt green',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__13__qzjhy1LGhN.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805817',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 2,
    reviews: 22,
    rating: 1.2,
    category: 'kids',
  },
  {
    id: 22,
    name: 'kids shirt orang',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__15__r-mhWhYa31.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805438',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 5,
    reviews: 33,
    rating: 1.2,
    category: 'kids',
  },
  {
    id: 23,
    name: 'kids shirt yellow',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__18__4kf4AvjYC.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805417',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 6,
    reviews: 44,
    rating: 1.5,
    category: 'kids',
  },
  {
    id: 24,
    name: 'kids shirt broun',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__14__e7tOymVEb.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805422',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 7,
    reviews: 56,
    rating: 3,
    category: 'kids',
  },
  {
    id: 25,
    name: 'kids shirt blue',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__12__a8_MmV5EU.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805418',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 8,
    reviews: 776,
    rating: 4.5,
    category: 'kids',
  },
  {
    id: 26,
    name: 'kids shirt black',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__11__ryaSrAEypv.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805334',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 12,
    reviews: 23,
    rating: 2.4,
    category: 'kids',
  },
  {
    id: 27,
    name: 'kids shirt white',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg_hI95ph-_t.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805269',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 13,
    reviews: 45,
    rating: 3.5,
    category: 'kids',
  },
  {
    id: 28,
    name: 'kids shirt grey',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__17__axi7ioYy5.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805143',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 125,
    reviews: 65,
    rating: 4,
    category: 'kids',
  },
  {
    id: 29,
    name: 'kids shirt pink',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__10__99qklMrvh.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805128',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 25,
    reviews: 767,
    rating: 4.6,
    category: 'kids',
  },
  {
    id: 30,
    name: 'kit shirts with differnet colors',
    image:
      'https://ik.imagekit.io/ievdkoh2e/shop_website/kids/pngegg__16__taHZoEbc8.png?ik-sdk-version=javascript-1.4.3&updatedAt=1663654805017',
    des: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero nulla deleniti aspernatur eligendi animi veritatis expedita voluptas tempora tempore eaque corporis, laudantium facere sapiente qui nobis laboriosam sunt possimus fuga!',
    price: 65,
    reviews: 122,
    rating: 4.3,
    category: 'kids',
  },
];
